<?php /** @var $proposal \models\Proposals */ ?>
<?php $this->load->view('global/header'); ?>
<style>

#content{
    line-height: 1.7em;
   
}
#top_menu{
    display:none;
}
#top_panel{
    display:none;
}
</style>
<div id="content" class="clearfix estimate-item-sheet materialize" xmlns="http://www.w3.org/1999/html">
<div class="et_pb_column et_pb_column_4_4 et_pb_column_0  et_pb_css_mix_blend_mode_passthrough et-last-child">
				
				
				<div class="et_pb_module et_pb_text et_pb_text_0  et_pb_text_align_left et_pb_bg_layout_light">
				
				
				<div class="et_pb_text_inner"><h4>Terms of Use</h4></div>
			</div> <!-- .et_pb_text --><div class="et_pb_module et_pb_text et_pb_text_1  et_pb_text_align_left et_pb_bg_layout_light">
				
				
				<div class="et_pb_text_inner"><p><?php echo SITE_NAME;?> &nbsp;LLC, on behalf of its parent, affiliates, subsidiaries and subcontractors, (“<?php echo SITE_NAME;?> &nbsp;LLC” or the “Company”) operates the company’s website (“Site”) to provide online access to information about the company and services provided. By accessing and using this Site, you agree to each of the terms and conditions set forth herein (“Terms of Use”). Additional terms and conditions applicable to specific areas of this Site, or to particular content or transactions, are also posted in particular areas of the Site and, together with these Terms of Use, govern your use of those areas, content or transactions. These Terms of Use, together with applicable additional terms and conditions, are referred to as this “Agreement.”</p>
<p><?php echo SITE_NAME;?> &nbsp;LLC reserves the right to modify this Agreement at any time without giving you prior notice. Your use of the Site following any such modification constitutes your agreement to follow and be bound by the Agreement as modified. The last date these Terms of Use were revised is set forth below.</p>
<p>You may not access the Services &nbsp;if You are Our direct competitor, except with Our prior written consent. In addition, You may not access the Services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.</p>
<p>In the event of change of ownership, addition of officers, directors or investors or part time employees with interest in any competitor company you are required to immediately contact us and gives us the immediate right to terminate your agreement without any reimbursement.</p>
<p><strong>1. Use of Site and Site Materials</strong></p>
<p>All Content on this Site (including, without limitation, text, design, graphics, logos, icons, images, audio clips, video clips, downloads, interfaces, code and software, interactive features and other materials, as well as the selection and arrangement thereof, singly or collectively, the “Content”), is the exclusive property of and owned by <?php echo SITE_NAME;?> &nbsp;LLC, its licensors or its content providers and is protected by copyright, trademark and other applicable laws. You may access and print the Content that you see, hear or otherwise experience on the Site to learn about <?php echo SITE_NAME;?> &nbsp;LLC and the services the Company offers (the “Services”), provided you do not modify or delete any copyright, trademark or other proprietary notice that appears on the material. No additional right, title or interest in any Content is transferred to you, whether as a result of accessing or printing such Content or otherwise. <?php echo SITE_NAME;?> &nbsp;LLC reserves complete title and all intellectual property rights in the Content. Except as expressly authorized by this Agreement, you may not use, alter, download, reproduce, upload, license, reverse engineer, copy, distribute, transmit, broadcast, display, sell, license, derive another work from or otherwise exploit any Content obtained from the Site</p>
<p>Any use of Content, or derivative works thereof, for purposes competitive to <?php echo SITE_NAME;?> &nbsp;LLC is expressly prohibited. You agree to abide by all additional restrictions displayed on the Site as it may be updated from time to time.</p>
<p>You agree not to use contact information provided on the Site for unauthorized purposes, including marketing. You further agree not to (i) use any hardware or software intended to damage or interfere with the proper working of the Site, (ii) surreptitiously intercept any system, data or personal information from the Site, or (iii) interrupt or attempt to interrupt the operation of the Site in any way.</p>
<p><strong>2. Copyright</strong></p>
<p>The Site and the Content are protected by U.S. and/or foreign copyright laws, and belong to <?php echo SITE_NAME;?> &nbsp;LLC or its partners, affiliates, contributors or third parties. The copyrights in the Content are owned by <?php echo SITE_NAME;?> &nbsp;LLC or other copyright owners who have authorized their use on the Site. You may download and reprint Content for non-commercial, non-public, personal use only, provided such Content is not manipulated or changed in any way. If you are browsing this Site as an employee or member of any business or organization, you may download and reprint Content only for educational or other non-commercial purposes within your business or organization, provided such Content is not manipulated or changed in any way other than attribution, which shall be readily visible thereon, except as otherwise permitted in writing by <?php echo SITE_NAME;?> &nbsp;LLC. You may not manipulate or alter in any way images or other Content on the Site.</p>
<p><strong>3. Accuracy, Completeness and Timeliness of Information on this Site</strong></p>
<p><?php echo SITE_NAME;?> &nbsp;LLC is not responsible for Content that is not accurate, complete or current. The Content is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on any portion of the Content is at your own risk. This Site may contain certain historical information. Historical information necessarily is not current and is provided for your reference only. <?php echo SITE_NAME;?> &nbsp;LLC reserves the right to modify the Content at any time, but has no obligation to update any Content.</p>
<p><strong>4. Trademarks</strong></p>
<p>You are prohibited from using any of the marks or logos appearing throughout the Site without permission from the trademark owner, except as permitted by applicable law.</p>
<p><strong>5. Links to Third-Party Websites</strong></p>
<p>Links on the Site to third-party websites or information are provided solely as a convenience to you. If you use these links, you will leave the Site. Such links do not constitute or imply an endorsement, sponsorship, or recommendation by <?php echo SITE_NAME;?> &nbsp;LLC of the third party, the third-party website, or the information contained therein. <?php echo SITE_NAME;?> &nbsp;LLC is not responsible for the availability of any such websites. <?php echo SITE_NAME;?> &nbsp;LLC is not responsible or liable for any such website or the content thereon, any loss or damage which may be incurred by you as a result of the availability of those websites, or as a result of any reliance placed by you on the completeness, accuracy or existence of any products or other materials on, or available from, such websites. If you use the links to the websites you will leave the Site, and will be subject to the terms of use and privacy policy applicable to those websites.</p>
<p><strong>6. Linking to this Site</strong></p>
<p>If you would like to link to the Site, you must follow <?php echo SITE_NAME;?> &nbsp;LLC link guidelines. Unless specifically authorized by <?php echo SITE_NAME;?> &nbsp;LLC, you may not connect “deep links” to the Site, i.e, create links to this site that bypass the home page or other parts of the Site. You may not mirror or frame the home page or any other pages of this Site on any other website or web page.</p>
<p><strong>7. Downloading Files</strong></p>
<p><?php echo SITE_NAME;?> &nbsp;LLC cannot and does not guarantee or warrant that files available for downloading through the Site will be free of infection by software viruses, trojans or other harmful computer code, files or programs.</p>
<p><strong>8. Software</strong></p>
<p>Any software available for download via the Site is the copyrighted work of <?php echo SITE_NAME;?> &nbsp;LLC and/or its licensors. Use of such software is governed by the terms of the end-user license agreement that accompanies or is included with the software. Downloading, installing, and/or using any such software indicates your acceptance of the terms of the end-user license agreement.</p>
<p><strong>9. Release</strong></p>
<p>The information on the Site and contained within the Content and the emphasis placed thereon solely reflect the opinion of <?php echo SITE_NAME;?> &nbsp;LLC and is not intended to necessarily address any specific concerns or interests that others may have. <?php echo SITE_NAME;?> &nbsp;LLC does not provide any representation or warranty as to (i) the accuracy or completeness of the Site or any of the Content, (ii) whether access and use of the Site will be uninterrupted, timely, secure or free from error, (iii) any protection from any bugs, viruses, trojan horses, or the like which may be transmitted to or through the Site; (iv) any errors or omissions in any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted, or otherwise made available via the Site; and/or (v) whether defects in the operation or functionality of any software on the Site will be corrected. <?php echo SITE_NAME;?> &nbsp;LLC does not warrant or represent that the Site or any Content is sufficient or appropriate for the purposes of any other party and all conditions, warranties, representations, terms and undertakings, express or implied, statutory or otherwise in respect of the Site or the Content for those purposes is hereby excluded.</p>
<p>In consideration for allowing YOU to use the SITE AND THE CONTENT, YOU specifically agree that <?php echo SITE_NAME;?> &nbsp;LLC shall have no liability for any losses or damages arising from or in any way related to the USE OF THE SITE OR ANY CONTENT incurred by YOU.&nbsp;YOU agree to waive, fully release, DEFEND and hold <?php echo SITE_NAME;?> &nbsp;LLC harmless from any claims which YOU may have arising in any way from use of THE SITE OR THE CONTENT including but not limited to claims for breach of contract, breach of warranty, strict liability, negligence, and/or negligent misrepresentation. YOU further AGREE TO waive and fully release, DEFEND AND HOLD <?php echo SITE_NAME;?> &nbsp;LLC HARMLESS from any and all consequential, indirect, special, incidental or punitive damages of any nature, including, but not limited to, loss of profits, loss of revenues, loss of goodwill, in connection with YOUR use of or reliance upon the SITE or any CONTENT regardless how such damages arise (including the negligence of <?php echo SITE_NAME;?> &nbsp;LLC in the preparation of the SITE OR CONTENT).&nbsp;The benefit of such releases, waivers or limitations of liability shall extend to <?php echo SITE_NAME;?> &nbsp;LLC and its subsidiaries, affiliates, subcontractors, and the directors, officers, partners, employees, and agents thereof. <?php echo SITE_NAME;?> &nbsp;LLC DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY CONTENT OR SOFTWARE PROVIDED BY A THIRD PARTY THROUGH THE SITE.</p>
<p><strong>10. Indemnification</strong></p>
<p>You understand and agree that you are personally responsible for your behavior on the Site. You agree to indemnify, defend and hold harmless <?php echo SITE_NAME;?> &nbsp;LLC, its parent companies, subsidiaries, affiliated companies, joint ventures, business partners, licensors, employees, agents, and any third-party information providers to the Site from and against all claims, losses, expenses, damages and costs (including, but not limited to, direct, incidental, consequential, exemplary and indirect damages), and reasonable attorneys’ fees, resulting from or arising out of (i) your use, misuse, or inability to use the Site, or the Content, or any violation by you of this Agreement; (ii) violation of any third party right by you, including, without limitation, any copyright, trademark, patent, property, or privacy right; or (iii) any claim that any Content caused damage to you or any third party you provided such Content.</p>
<p><strong>11. Privacy</strong></p>
<p>Please see&nbsp;Privacy Policy on Website</p>
<p><strong>12. User Conduct</strong></p>
<p>You agree to use the Site only for lawful purposes. You agree not to take any action that might compromise the security of the Site, render the Site inaccessible to others or otherwise cause damage to the Site or the Content. You agree not to add to, subtract from, or otherwise modify the Content, or to attempt to access any Content that is not intended for you. You agree not to use the Site in any manner that might interfere with the rights of third parties.</p>
<p>Some features that may be available on this site require registration. In order to use such features, you agree to register as required and provide true, accurate, current and complete information about yourself.</p>
<p>Some features on this site require use of a password. You are responsible for protecting your password. You agree that you will be responsible for any and all statements made, and acts or omissions that occur, through the use of your password. If you have any reason to believe or become aware of any loss, theft or unauthorized use of your password, you agree to notify <?php echo SITE_NAME;?> &nbsp;LLC immediately. <?php echo SITE_NAME;?> &nbsp;LLC may assume that any communications <?php echo SITE_NAME;?> &nbsp;LLC receives under your password have been made by you unless <?php echo SITE_NAME;?> &nbsp;LLC receives notice otherwise.</p>
<p>You or third parties acting on your behalf are not allowed to use <?php echo SITE_NAME;?> &nbsp;LLC proprietary marks as meta tags, without <?php echo SITE_NAME;?> &nbsp;LLC’s written consent. These marks include, but are not limited to, “<?php echo SITE_NAME;?> &nbsp;LLC,” “B&amp;V,” B&amp;V logos and “<em>Building a World of Difference.</em>” You may not use techniques or technology to enclose any Content or any portion of the Site (commonly known as “framing”) without <?php echo SITE_NAME;?> &nbsp;LLC’s express written consent. Further, you may not utilize any Content in any meta tags or any other “hidden text” techniques or technologies without <?php echo SITE_NAME;?> &nbsp;LLC’s express written consent.</p>
<p><strong>13. General Provisions</strong></p>
<p>a. Entire Agreement/No Waiver. These Terms of Use constitute the entire agreement of the parties with respect to the subject matter hereof and replaces all prior agreements or understandings, representations or warranties (if any) between the parties. No waiver by <?php echo SITE_NAME;?> &nbsp;LLC of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. Should any term or provision of these Terms of Use be deemed or held to be invalid or unenforceable, the remaining terms and provisions shall continue in full force and effect.</p>
<p>b. Correction of Errors and Inaccuracies. The Content may contain typographical errors or other errors or inaccuracies and may not be complete or current. <?php echo SITE_NAME;?> &nbsp;LLC therefore reserves the right to correct any errors, inaccuracies or omissions and to change or update the Content at any time without prior notice. <?php echo SITE_NAME;?> &nbsp;LLC does not, however, guarantee that any errors, inaccuracies or omissions will be corrected.</p>
<p>c. The validity and effect of these Terms of Use shall be governed by, and construed and enforced in accordance with, the laws of OHIO without regard to its conflicts or choice of laws principles. ANY SUIT, ACTION OR PROCEEDING CONCERNING OR RELATING TO THE PROJECT CENTRAL WEBSITE, ITS USE, THESE TERMS OF USE, ANY SALE OR ANY OTHER PRODUCT, SERVICE, POLICY OR PROCEDURE OF <?php echo SITE_NAME;?> &nbsp;LLC, MUST BE BROUGHT EXCLUSIVELY IN A COURT OF COMPETENT JURISDICTION IN HAMILTON COUNTY, OHIO, AND YOU HEREBY IRREVOCABLY CONSENT TO THE JURISDICTION OF SUCH COURT (AND OF THE APPROPRIATE APPELLATE COURTS THEREFROM) IN ANY SUCH SUIT, ACTION OR PROCEEDING, YOU IRREVOCABLY WAIVE, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY OBJECTION WHICH YOU MAY NOW OR HEREAFTER HAVE TO THE LAYING OF VENUE OF ANY SUCH SUIT, ACTION OR PROCEEDING IN ANY SUCH COURT OR THAT ANY SUCH SUIT, ACTION OR PROCEEDING WHICH IS BROUGHT IN ANY SUCH COURT HAS BEEN BROUGHT IN AN INCONVENIENT OR IMPROPER FORUM.</p>
<p><strong>14. Global Availability</strong></p>
<p>Information <?php echo SITE_NAME;?> &nbsp;LLC publishes on the World Wide Web may contain references or cross references to <?php echo SITE_NAME;?> &nbsp;LLC products, programs and services that are not announced or available in your country. Such references do not imply that <?php echo SITE_NAME;?> &nbsp;LLC intends to announce or make available such products, programs, or services in your country. Please consult your local <?php echo SITE_NAME;?> &nbsp;LLC business contact for information regarding the products, programs and services that may be available to you.</p>
<p><strong>15. Translations</strong></p>
<p>Certain text in this website may be made available in languages other than English. Text may be translated by a person or solely by computer software with no human intervention or review. These translations are provided as a convenience to you, and <?php echo SITE_NAME;?> &nbsp;LLC makes no representations or commitments regarding the accuracy or completeness of the translation, whether or not computer-generated or performed by a person.</p>
<p>Content Distribution</p>
<p>As a User you are entitled to use the MR Content currently posted on the MR at the time of use in accordance with these Terms of Use, any terms and conditions applicable to any MR Content Listing and any applicable ThirdParty Terms, however your status as a User does not entitle you to be an MR Content Provider or to distribute your own MR Content through the MR. If you are the owner or authorized licensee of Content that you wish to make available on the MR, please contact info@<?php echo SITE_NAME;?> for additional information.</p>
<p>Copyright Agent</p>
<p>If you believe that any information on <?php echo SITE_NAME;?>.com has been used in a manner not authorized by you and that constitutes copyright infringement, please provide <?php echo SITE_NAME;?> &nbsp;LLC’s Copyright Agent with a written notice that includes the following information:</p>
<ul>
<li>an electronic or physical signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed;</li>
<li>identification of the copyrighted work claimed to have been infringed;</li>
<li>a description of where the material that you claim is infringing is located on the MR;</li>
<li>your address, telephone number, and e-mail address;</li>
<li>a statement by you that has a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
<li>a statement by you, under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.</li>
</ul>
<p><?php echo SITE_NAME;?> &nbsp;LLC’s designated agent for notice of copyright infringement can be reached at:</p>
<p>Attn: Media Contact/Corporate Communications</p>
<p>RapidInjection LLC/<?php echo SITE_NAME;?> &nbsp;LLC<br>3814 West Street Suite 300<br>Cincinnati, Ohio 45227<br>Email:&nbsp;<a href="mailto:info@<?php echo SITE_EMAIL_DOMAIN;?>">info@<?php echo SITE_EMAIL_DOMAIN;?></a></p>
<p>Trademarks</p>
<p>The trademarks, service marks and logos displayed&nbsp; (the “Marks”) are owned by <?php echo SITE_NAME;?> &nbsp;LLC, MR Content Providers or other licensors, and may be displayed or otherwise used by you only as part of the editorial products which incorporate such Marks within <?php echo SITE_NAME;?>.com . All other uses require the prior written consent of <?php echo SITE_NAME;?> &nbsp;LLC.</p>
<p>Changes: Discontinuation</p>
<p><?php echo SITE_NAME;?> &nbsp;LLC reserves the right to change modify, add, or remove portions of these Terms of Use and/or the Privacy Policy at any time and such changes shall be effective upon posting the revised Terms of Use and/or Privacy Policy on the MR and <?php echo SITE_NAME;?> site. You agree to be responsible for periodically checking these Terms of Use and Privacy Policy for changes. Your continued use of the MR following the posting of changes constitutes your acceptance of those changes. <?php echo SITE_NAME;?> &nbsp;LLC may change, suspend or discontinue any aspect of the MR at any time, without prior notice and without any liability to you.</p></div>
			</div> <!-- .et_pb_text -->
			</div>




</div>


<?php $this->load->view('global/footer'); ?>
<script src='/static/js/inputmask.js'></script>
